{% set name = "intake-thredds" %}
{% set version = "2022.8.19" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/intake-thredds-{{ version }}.tar.gz
  sha256: f94d121ed1c72424bef16be73cb347d4d72aac137d318a0c6281cff64ed61b03

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=30.3.0
    - setuptools_scm
  run:
    - aiohttp >=3.7
    - fsspec >=0.8.5
    - h5netcdf >=0.8.1
    - intake >=0.6.0
    - intake-xarray >=0.3
    - pydap
    - python >=3.7
    - siphon
    - tqdm

test:
  imports:
    - intake_thredds
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://github.com/intake/intake-thredds
  summary: Intake interface to THREDDS data catalogs
  description: |
    Intake interface to THREDDS data catalogs
  doc_url: https://intake-thredds.readthedocs.io/en/latest/
  dev_url: https://github.com/intake/intake-thredds
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andersy005
    - aaronspring
